services:
  database:
    image: postgres:16
    container_name: suqly-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: suqly
      POSTGRES_PASSWORD: password
      POSTGRES_DB: suqly
    volumes:
      - suqly_db_data:/var/lib/postgresql/data

volumes:
  suqly_db_data: